name: Generate-Super-Scientific-Atomic-JAR
on:
  workflow_dispatch:

jobs:
  forge_process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - run: |
          cat <<EOF > builder.gradle
          plugins {
              id 'java-library'
              id 'com.gradleup.shadow' version '8.3.4'
          }
          repositories {
              mavenCentral()
              google()
              maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
          }
          dependencies {
              implementation 'org.matheclipse:matheclipse-core:3.2.0'
              implementation 'org.hipparchus:hipparchus-core:4.1'
              implementation 'org.apfloat:apfloat:2.0.1'
              implementation 'com.google.guava:guava:33.3.1-android'
              runtimeOnly 'com.celeral:log4j-android-api:1.0.0'
          }
          shadowJar {
              zip64 true
              mergeServiceFiles()
              archiveFileName = 'MASTER-COMMAND-MATH-3-6-NEW.jar'
          }
          EOF
          gradle shadowJar -b builder.gradle

      - uses: actions/upload-artifact@v4
        with:
          name: MATH-LEGACY-POWERED-JAR
          path: build/libs/*.jar
